In [1]:
from sem import SEM
import numpy as np
import matplotlib
import matplotlib.pyplot as plt

opts = {'lambda': 10, 'alpha': 0.1, 'beta': 0.00001, 'eta': 0.01, 'tau': 0.1}

s = SEM(opts)

X = [[1, 1]] * 10 + [[-1, -1]] * 10

e, post = s.segment(X)

[1, 1]


x =  [1, 1]
K =  0
e hat =  []
prior =  [ 1.]
x_s'[ 0 ] =  [0, 0]
lik =  [ 0.]
post =  [ 1.]
[1, 1]


x =  [1, 1]
K =  1
e hat =  [0]
C =  [1]
prior =  [ 0.99099099  0.00900901]
x_s'[ 0 ] =  [1.0, 1.0]
x_s'[ 1 ] =  [1.0, 1.0]
lik =  [ 15915.49430919  15915.49430919]
post =  [ 0.99099099  0.00900901]
[[ 0.]
 [ 0.]]
[[ 1.  0.]
 [ 0.  1.]]
[1, 1]


x =  [1, 1]
K =  1
e hat =  [0, 0]
C =  [2]
prior =  [ 0.99173554  0.00826446]
x_s'[ 0 ] =  [1.0, 1.0]
x_s'[ 1 ] =  [1.0, 1.0]
lik =  [ 15915.49430919  15915.49430919]
post =  [ 0.99173554  0.00826446]
[[ 0.]
 [ 0.]]
[[ 1.  0.]
 [ 0.  1.]]
[1, 1]


x =  [1, 1]
K =  1
e hat =  [0, 0, 0]
C =  [3]
prior =  [ 0.99236641  0.00763359]
x_s'[ 0 ] =  [1.0, 1.0]
x_s'[ 1 ] =  [1.0, 1.0]
lik =  [ 15915.49430919  15915.49430919]
post =  [ 0.99236641  0.00763359]
[[ 0.]
 [ 0.]]
[[ 1.  0.]
 [ 0.  1.]]
[1, 1]


x =  [1, 1]
K =  1
e hat =  [0, 0, 0, 0]
C =  [4]
prior =  [ 0.9929078  0.0070922]
x_s'[ 0 ] =  [1.0, 1.0]
x_s'[ 1 ] =  [1.0, 1.0]
lik =  [ 15

In [2]:
K = len(post[-1])
p = np.zeros((len(post), K));
for i in range(len(post)):
    p[i,0:len(post[i])] = post[i]
print p

[[  1.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  9.90990991e-01   9.00900901e-03   0.00000000e+00]
 [  9.91735537e-01   8.26446281e-03   0.00000000e+00]
 [  9.92366412e-01   7.63358779e-03   0.00000000e+00]
 [  9.92907801e-01   7.09219858e-03   0.00000000e+00]
 [  9.93377483e-01   6.62251656e-03   0.00000000e+00]
 [  9.93788820e-01   6.21118012e-03   0.00000000e+00]
 [  9.94152047e-01   5.84795322e-03   0.00000000e+00]
 [  9.94475138e-01   5.52486188e-03   0.00000000e+00]
 [  9.94764398e-01   5.23560209e-03   0.00000000e+00]
 [  9.95024876e-01   4.97512438e-03   0.00000000e+00]
 [  8.92154394e-16   1.00000000e+00   0.00000000e+00]
 [  4.21008079e-18   9.90990991e-01   9.00900901e-03]
 [  3.86214023e-18   9.91735537e-01   8.26446281e-03]
 [  3.56732037e-18   9.92366412e-01   7.63358779e-03]
 [  3.31431892e-18   9.92907801e-01   7.09219858e-03]
 [  3.09482760e-18   9.93377483e-01   6.62251656e-03]
 [  2.90260229e-18   9.93788820e-01   6.21118012e-03]
 [  2.73285946e-18   9.94152

In [4]:
plt.plot(p)
#plt.legend([''])
plt.xlabel('t')
plt.ylabel('P(e|s_{1:t})')
plt.show()

RuntimeError: LaTeX was not able to process the following string:
'P(e|s_{1:t})'

Here is the full report generated by LaTeX:
This is pdfTeX, Version 3.14159265-2.6-1.40.18 (TeX Live 2017) (preloaded format=latex)
 restricted \write18 enabled.
entering extended mode
(./1ebb3db88b736b01c7dc30ea52f80e0d.tex
LaTeX2e <2017-04-15>
Babel <3.10> and hyphenation patterns for 84 language(s) loaded.
(/usr/local/texlive/2017/texmf-dist/tex/latex/base/article.cls
Document Class: article 2014/09/29 v1.4h Standard LaTeX document class
(/usr/local/texlive/2017/texmf-dist/tex/latex/base/size10.clo))
(/usr/local/texlive/2017/texmf-dist/tex/latex/type1cm/type1cm.sty)
(/usr/local/texlive/2017/texmf-dist/tex/latex/base/textcomp.sty
(/usr/local/texlive/2017/texmf-dist/tex/latex/base/ts1enc.def))
(/usr/local/texlive/2017/texmf-dist/tex/latex/ucs/ucs.sty
(/usr/local/texlive/2017/texmf-dist/tex/latex/ucs/data/uni-global.def))
(/usr/local/texlive/2017/texmf-dist/tex/latex/base/inputenc.sty
(/usr/local/texlive/2017/texmf-dist/tex/latex/ucs/utf8x.def))
(/usr/local/texlive/2017/texmf-dist/tex/latex/geometry/geometry.sty
(/usr/local/texlive/2017/texmf-dist/tex/latex/graphics/keyval.sty)
(/usr/local/texlive/2017/texmf-dist/tex/generic/oberdiek/ifpdf.sty)
(/usr/local/texlive/2017/texmf-dist/tex/generic/oberdiek/ifvtex.sty)
(/usr/local/texlive/2017/texmf-dist/tex/generic/ifxetex/ifxetex.sty)

Package geometry Warning: Over-specification in `h'-direction.
    `width' (5058.9pt) is ignored.


Package geometry Warning: Over-specification in `v'-direction.
    `height' (5058.9pt) is ignored.

)
No file 1ebb3db88b736b01c7dc30ea52f80e0d.aux.
(/usr/local/texlive/2017/texmf-dist/tex/latex/base/ts1cmr.fd)
(/usr/local/texlive/2017/texmf-dist/tex/latex/ucs/ucsencs.def)
*geometry* driver: auto-detecting
*geometry* detected driver: dvips
! Missing $ inserted.
<inserted text> 
                $
l.13 ...ize{10.000000}{12.500000}{\sffamily P(e|s_
                                                  {1:t})}
! Extra }, or forgotten $.
l.13 ...000000}{12.500000}{\sffamily P(e|s_{1:t})}
                                                  
! Missing $ inserted.
<inserted text> 
                $
l.14 \end{document}
                   
[1] (./1ebb3db88b736b01c7dc30ea52f80e0d.aux) )
(\end occurred inside a group at level 1)

### simple group (level 1) entered at line 13 ({)
### bottom level
(see the transcript file for additional information)
Output written on 1ebb3db88b736b01c7dc30ea52f80e0d.dvi (1 page, 388 bytes).
Transcript written on 1ebb3db88b736b01c7dc30ea52f80e0d.log.
 

